version: '3'

volumes:
  postgres-data-volume:
    external: true

services:
  pg:
    build: ./docker/pg
    image: oscar60310/pg-sc2
    volumes:
      - postgres-data-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: sctest
    ports:
      - 5432:5432
    restart: always
  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://pg/sctest -user=sctest -password=sctest -connectRetries=60 migrate
    volumes:
      - ./migrations:/flyway/sql
    depends_on:
      - pg
