version: '3'

volumes:
  postgres:
    external: true

services:
  pg:
    image: oscar60310/pg-sc2
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: sctest
    ports:
      - 5432:5432
  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://pg/sctest -user=sctest -password=sctest -connectRetries=60 migrate
    volumes:
      - ./migrations:/flyway/sql
    depends_on:
      - pg
  web:
    image: oscar60310/shipment-creator-2:1.0.0
    ports:
      - 3000:3000
    environment:
      NODE_ENV: production
    volumes:
      - C:/Users/oscar/projects/sc-volume/config:/sc-web/config
    depends_on:
      - pg
      - flyway