version: 2.1
jobs:
  lint:
    docker:
      - image: node:10.16.3-alpine
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: npm install
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run: # run lint
          name: lint
          command: npm run lint

workflows:
  version: 2
  test_and_release:
    jobs:
      - test:
          filters:
            branches:
              only:
                - master
                - develop
