version: 2.1
jobs:
  lint:
    docker:
      - image: node:10.16.3-alpine
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: npm install
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run: # run lint
          name: lint
          command: npm run lint
  build:
    docker:
      - image: node:10.16.3-alpine
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: npm install
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: build
          command: sh build.sh
      - persist_to_workspace:
          root: /tmp/build
          paths:
            - build
  release:
    docker:
      - image: node:10.16.3-alpine
    steps:
      - attach_workspace:
          at: /tmp
      - run:
          name: test
          command: ls /tmp

workflows:
  version: 2
  test_and_release:
    jobs:
      - lint:
          filters:
            branches:
              only:
                - master
                - develop
                - feature/auto-release
      - build:
          requires:
            - lint
          filters:
            branches:
              only:
                - feature/auto-release
      - release:
          requires:
            - build
          filters:
            branches:
              only:
                - feature/auto-release
