version: 2.1
jobs:
  lint:
    docker:
      - image: node:10.16.3-alpine
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: npm install
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run: # run lint
          name: lint
          command: npm run lint
  build:
    docker:
      - image: node:10.16.3-alpine
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: npm install
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: build
          command: sh build.sh
      - persist_to_workspace:
          root: ./build
          paths:
            - ./*
  release:
    docker:
      - image: oscar60310/release-kit:1.0.1
    steps:
      - checkout
      - attach_workspace:
          at: /root/project/build
      - run:
          name: create folder
          command: mkdir dist
      - run:
          name: bundle
          command: zip -r dist/shipment-creator.zip build/*
      - run:
          name: set user
          command: git config --global user.name $CIRCLE_USERNAME
      - run:
          name: set email
          command: git config --global user.email $CIRCLE_USERNAME"@gmail.com"
      - run:
          name: release
          command: npm run release
workflows:
  version: 2
  test_and_release:
    jobs:
      - lint
      - build:
          requires:
            - lint
          filters:
            branches:
              only:
                - master
      - release:
          requires:
            - build
          filters:
            branches:
              only:
                - master
